spring.application.name=healthCenter
spring.datasource.url=jdbc:postgresql://localhost:5432/health_center
spring.datasource.username=postgres
spring.datasource.password=Bilmuh100

# Hibernate / JPA Ayarlari
# Bu ayar Java siniflarini otomatik olarak pgAdmin'de tabloya donusturur.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect